### ISSUE TITLE
Repetition of Links

### ISSUE THREAD

**Issue by MattShilling** [ericlighthofmann/EdgarScrape#1]
Because there are two exact same Form 4 entries, from both the person exchanging the stock and from the company affected, under slightly different URLs, the list in stocks_sent will not pick up that we have already sent the link to be scraped before. 

the last 50 characters are the same so I would suggest this change; did the trick for me

`last50 = slice(-50, None)`
`if link[last50] not in stocks_sent:
       ...
       stocks_sent.append(link[last50])`

**Comment by ericlighthofmann** [comment]
Hey - great idea, thank you! There's a couple of other changes I made regarding punctuation in the company name which would miss matches. I'll commit again in a second. Thanks again for the heads up.

Edit: Disregard all that - you're correct :)
